### ISSUE TITLE
Define grace time between drain and reboot

### ISSUE THREAD

**Issue by andrsp** [weaveworks/kured#121]
Sometimes reboot occurs too quickly and pods on drained node stuck at terminating state before node comes back.

Could you please add some option to define a grace period to complete drain (wait for evicted pods to be running on different nodes) and then proceed to reboot?

It also can be achieved by custom drain command (which is hardcoded now)

**Comment by bboreham** [comment]
What sort of time are you talking about?
Do you have `terminationGracePeriodSeconds` set high enough in your pod spec?

**Comment by sebikul** [comment]
In our situation, we need a few seconds from when a node is completely drained, to when it is shut down. Explaining the setup as easily as possible, we have an nginx Ingress installed as a DaemonSet with hostPort to receive traffic from an L4 load balancer.

Once the node is drained, we detect this situation and start sending failed health probes to our cloud provider, thus removing the current instance from the backend pool of the load balancer. However, this probes are being sent every 5 seconds, and a down situation requires two consecutive failed probes. This means that we still need to be able to process requests for at least 10 seconds, plus the time it takes for the answer to come back, to prevent any kind of downtime, or lost request, during the reboot process.

In this case, waiting ~15 seconds from when the node is drained until it reboots would ensure that more than 99% of the requests that could have been in flight have already been answered, and that no more requests are being routed. Otherwise we have ~10 seconds of requests being sent to a node that is currently rebooting, but that the load balancer has not yet seen as down.

**Comment by bboreham** [comment]
Have you tried adding a `preStop` hook to wait the 15 seconds?

**Comment by dholbach** [comment]
We recently put in https://github.com/weaveworks/kured/commit/1ba3acab98fa217ea65405640706c55c89be956d so it should be easier to implement now?

**Comment by unixfox** [comment]
Bump

**Comment by evrardjp** [comment]
@unixfox Can you give more context for your case? Did you use, for example, what @bboreham has mentioned? Can you clarify your expectations?

**Comment by stmaute** [comment]
Any news on this? It would be nice to have an option to configure a grace time between draining the pods and restarting the VM.

**Comment by bboreham** [comment]
@stmaute please explain why you want this, including why the standard Kubernetes techniques already mentioned are not applicable for you.

**Comment by stmaute** [comment]
A configurable time between draining and restart would give some more flexibility to complete connection draining and other stuff.
But in my case I got the problem solved with a pre-stop hook.

**Comment by bboreham** [comment]
I conclude that adding the feature to kured would be the wrong step, since a preStop hook works in every case that a component needs to wait for draining.
