### ISSUE TITLE
What's the behavior when there is only one node in k8s cluster

### ISSUE THREAD

**Issue by leonard520** [weaveworks/kured#145]
Hi all,

I am testing that if there is only one node in k8s cluster, will kured still work?
In my testing, looks kured drain all the pods but later the node stuck in "Ready,SchedulingDisabled". all the pods also stuck in pending status. Is it expected?

**Comment by cloudoutloud** [comment]
The node being stuck in `Ready,SchedulingDisabled` is usually due to pod distribution budget set on the cluster. If there are some deployments which had this set Kured will have trouble evicting pods.
Run `kubectl get pdb -A` to view.
As you only have a one-node cluster if the node is in `Ready,SchedulingDisabled` state no pods will able to be scheduled hence all pods stuck in pending.

**Comment by RalphNguyen** [comment]
Hi, I'm having the same issue.
When running kubectl get pdb -A , I found coredns-pdb in kube-system namespace has Min Available = 1. This stops the only one node in the AKS cluster from being drained.
Is there anyway I could come over this issue?
My AKS version: 1.16.7 and Kure: 1.4.0
Thanks a lot.

**Comment by cloudoutloud** [comment]
If you only have a one-node cluster, your best bet is to disable/remove the PDB for core-dns then this would not cause any issues with Kured.

**Comment by evrardjp** [comment]
Should we close it?

Does it work better with @cloudoutloud 's fix?
