### ISSUE TITLE
Kured induced restart won't launch latest version of the Linux node in default/system node pool

### ISSUE THREAD

**Issue by ammarqq** [weaveworks/kured#147]
We have an AKS cluster with Linux nodes and Kured installed to automatically restart nodes when a new security update is available. when applying security patches to the system (AKS default) node pool, the newly launched instance has an older kernel version and is scheduled to be restarted again. This usually lasts from a few hours to a few days and the instance gets restarted multiple times a day (sometimes each hour). 

![image](https://user-images.githubusercontent.com/18486257/84431316-c7959500-ac33-11ea-8a46-c6c8fc4cc3ba.png)

All the recently launched nodes (aks-default-13875295-vmss00000c, aks-syrup-13875295-vmss000007) were restarted to get the latest kernel updates (4.15.0-1089-azure) but they are still running old version (4.15.0-1082-azure). 

The high value of the last digit in e. g. aks-default-13875295-vmss00000c indicates that it was the 12th reboot in a row and is still running an older version and will be scheduled to reboot again.

**Comment by ondrejhlavacek** [comment]
Hi everyone, I am the original reporter via MS Azure support. I'll try describing what happens as we're getting dozens of reboots every day and it's pretty annoying. This is a screenshot of our Slack channels that monitors Kured restarts.

![image](https://user-images.githubusercontent.com/497675/84564714-03c81300-ad64-11ea-9dd9-d286fba1bea2.png)

Both mentioned node pools have 1 or 2 nodes. 

The `aks-syrup-***-vmss-**07` node is scheduled to reboot at 9:17 am. It starts to move all pods to another nodes in the same node pool. Since there is no available node to host all evicted pods from, the node pool is scaled up (we have autoscaling set up) and launches a new node, `aks-syrup-***-vmss-**08`. Then it successfully moves all pods from `***07` to other nodes and `***07` reboots. Since the `***07` node reboots empty, autoscaling turns it off immediately. 

Then the same repeats for the new node, `aks-syrup-***-vmss-**08` at 9:58. Scaling up with node `aks-syrup-***-vmss-**09`, moving all pods there and turning off `aks-syrup-***-vmss-**08`. And then again at 11:20 am and 12:23 pm and 1:51 pm. 

It seems like the new nodes do not have the latest security updates and are immediately marked to reboot. Most likely there's a difference between the security patch availability in different scenarios (patching existing nodes vs launching new nodes). Do you have suggestions how to prevent this from happening?

**Comment by nerijusk** [comment]
I'm seeing same issue. Also running Azure AKS with auto-scaling and multiple node pools.

**Comment by evrardjp** [comment]
From the `kured` perspective, kured does the right thing: if the node needs reboot (which is the case, even for the fresh one), then it triggers the reboot. Of course this is wrong, but I think this needs a collaboration work between Azure AKS and kured.

@dholbach do you know who can we ping for this?
