### ISSUE TITLE
Docker Tag Names

### ISSUE THREAD

**Issue by unly** [weaveworks/kured#33]
The Docker image tags available at https://quay.io/repository/weaveworks/kured?tab=tags are challenging. Based on the tag name or information given I can hardly identify what version is running. Especially difficult considering upgrading a Kubernetes cluster to a new version. In this case I would like to update kured to a newer version as well; preferably to the respective kubectl version. Docker tags would help to identify the right version of kured to deploy.

**Comment by awh** [comment]
Yes, sorry about this - it's essentially an artefact of the fact that we continuously deploy kured internally, so there's no pressure on me to make external releases. The original plan was to tag an official release every time a new minor version of kubernetes came out, and publish the corresponding manifest on the [release](https://github.com/weaveworks/kured/releases) page, but as you can see I didn't keep up with that commitment. I'm about to do a formal release based on 1.12.x kubectl/client-go - watch this space. 

Probably the right thing for me to do is to change our internal process so that master builds are deployed continuously to our development environment, but only deploy semver tagged builds to production to give myself motivation :smile:

**Comment by unly** [comment]
I just realized another great option besides tags for Docker images would be a compatibility matrix matching kured to the kubernetes releases. Tags would stay the same and information would still be easy to access.

Looking forward to a new release 👍

**Comment by awh** [comment]
https://github.com/weaveworks/kured/releases/tag/1.1.0 as promised.
