### ISSUE TITLE
Introduce resource limits to the kured helm chart 

### ISSUE THREAD

**Issue by IgorOrmus** [weaveworks/kured#434]
Considered best practice for kubernetes environments we recently started reporting against missing limits via azure policy in running clusters and kured was flagged up. Although possible to fix by manually editing the daemonset it would be good if the limits were added to the default helm chart as when the policy starts enforcing it will prevent kured from being auto deployed to new environments .

**Comment by ckotzbauer** [comment]
Hm, I'm not sure if this is really best practice to enfore default requests and limits in a Helm-Chart. Most of the charts out there do not have default values set for this, as it's up to the cluster-operators to manage this for their specific use-case.
Any thoughts on this?

**Comment by ckotzbauer** [comment]
> Hm, I'm not sure if this is really best practice to enfore default requests and limits in a Helm-Chart. Most of the charts out there do not have default values set for this, as it's up to the cluster-operators to manage this for their specific use-case.
Any thoughts on this?

WDYT? @dholbach @jackfrancis @evrardjp
@marosset Do you know if the resource-consumption would be considerably different on windows?

**Comment by marosset** [comment]
> > Hm, I'm not sure if this is really best practice to enfore default requests and limits in a Helm-Chart. Most of the charts out there do not have default values set for this, as it's up to the cluster-operators to manage this for their specific use-case.
> > Any thoughts on this?
> 
> WDYT? @dholbach @jackfrancis @evrardjp @marosset Do you know if the resource-consumption would be considerably different on windows?

Resource consumption does work differently on Windows.

Windows containers consume more resources than linux container and I think 250m cpu/250Mi mem are the minimum value that should be set for CPU limits. 

On Windows requests are used for scheduling but do not guarantee those resources on overprovisioned nodes. 
Eviction does not currently work on Windows either and we have seen stability issues when nodes become too overprovisioned.
Because of this, for workloads we always recommend starting with only limits and only add requests if you really understand your workloads and are trying to tune them for maximum capacity.
For daemonSets we probably do want to specify a small value for requests so that more node-allocatable resources can be reserved for actual workloads - 100m/100Mi would probably be good starting values for requests on windows containers.
