### ISSUE TITLE
Aqua Scan reports CVEs in kured image v1.10.1

### ISSUE THREAD

**Issue by kgusarov** [weaveworks/kured#621]
Hi!

Some time ago we've encountered incident on our production clusters when automated scan basically "exploded" creating several critical Security Alerts. Attaching screenshot of the report:

![image](https://user-images.githubusercontent.com/1231997/185567817-12e3302f-7977-4c4a-86d1-ca8432c530e7.png)

**Comment by ckotzbauer** [comment]
Hi,
with the next kured release, these CVEs would be fixed automatically. But currently there's no new release planned and we don't rebuild images without release right now.
If these CVEs are important to you and you need a fresh image, you can build it by yourself. It is not pretty easy. See #608 for more information.

**Comment by kgusarov** [comment]
This is more of a bureaucracy and internal policy question - since this is image we do not own, we are not really allowed to do anything except creating issues in GitHub. Otherwise the code would have to be in internal BitBucket. Building image is not hard, "legalizing" it - is.

**Comment by ckotzbauer** [comment]
Okay, thanks for the explanation.

**Comment by dholbach** [comment]
Should be fixed with the recent 1.10.2 release.

**Comment by evrardjp** [comment]
@kgusarov  -- This is an open source project, what you make out of it ... is yours :)

We provide the images "as is". I think this is important to note, and keep for the record.
We try to have the latest images always secure. This is why the images are scanned for CVE before publication, and during the cycle on a periodic basis.

The definition of security (and the policy) in your organisation is yours only. We can't do anything about it.
Please allow me to do a recommendation. I strongly encourage the security team in your organisation to: 1) be more 'proactive' (fix issues instead of just reporting, this would avoid the need to 'wait' for an unreasonable amount of time for your org); 2) be more 'autorithative' (have the ability to 'manage your destiny' or manage the code at your pace. And of course contributions back to this projects are welcome, see point 1) 

Other relevant information: We don't have a backport policy to fix older images. I am doubting this will change, unless we change our branching policy. AFAIK, this is not on the menu. If this is conflicting with the fact that you eventually might be running an older kubernetes version, with an older kured version, then it is something you need to be aware of.

**Comment by kgusarov** [comment]
> @kgusarov -- This is an open source project, what you make out of it ... is yours :)
> 
> We provide the images "as is". I think this is important to note, and keep for the record. We try to have the latest images always secure. This is why the images are scanned for CVE before publication, and during the cycle on a periodic basis.
> 
> The definition of security (and the policy) in your organisation is yours only. We can't do anything about it. Please allow me to do a recommendation. I strongly encourage the security team in your organisation to: 1) be more 'proactive' (fix issues instead of just reporting, this would avoid the need to 'wait' for an unreasonable amount of time for your org); 2) be more 'autorithative' (have the ability to 'manage your destiny' or manage the code at your pace. And of course contributions back to this projects are welcome, see point 1)
> 
> Other relevant information: We don't have a backport policy to fix older images. I am doubting this will change, unless we change our branching policy. AFAIK, this is not on the menu. If this is conflicting with the fact that you eventually might be running an older kubernetes version, with an older kured version, then it is something you need to be aware of.

You underestimate bureaucracy in large organizations :) Security team is keeping track of 100s of projects and they want responsible projects to fix everything. And once again - for the images we build we'd have to store source code in internal BitBucket. I cannot simply download executable from GitHub, since there is no source code for it. This is the main problem :)

**Comment by dholbach** [comment]
I think this is fixed in kured 1.10.2, no?

**Comment by evrardjp** [comment]
@dholbach while the cause of the initial issue is fixed in 1.10.2, I think it's fair to explain to rationale on 'how we work' for the users. This is why we are communicating on a closed issue, rather than reopening the issue.

**Comment by evrardjp** [comment]
@kgusarov haha, bureaucracy ... :) More seriously, you can really build the executable and it's really not hard. If you need your build system to be completely airgapped, then you will most likely need to vendor the dependencies (or mirror them), but outside that, it should be pretty easy to clone/vendor/build/publish internally, if you have such requirements.
