### ISSUE TITLE
document kured version upgarde process- in readme

### ISSUE THREAD

**Issue by namithcc** [weaveworks/kured#627]
Can we add upgrade process for version in readme. Eg from 1.7.0 to 1.10.2. Is it a direct upgrade (minor version)
How it is for a major version upgarde if there is?

**Comment by ckotzbauer** [comment]
In general, the changelog has all information you need for updating kured in-place (directly). There are no breaking-changes in patch- or minor-releases (if not written down otherwise).
If you use Helm as installation method, please check the Chart-README. There was one major-release a few weeks ago, which requires a reinstallation. But the process is described there. Apart from that the Helm-Chart also does not need any special handling.

**Comment by ckotzbauer** [comment]
Closed for now
